export const CHANGE_LOADING = "CHANGE_LOADING";
export const ADD_TASK = "ADD_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const TASK_COMPLETED = "TASK_COMPLETED";
export const CHANGE_CUSTOM_MODAL ='CHANGE_CUSTOM_MODAL'
export const SHOW_SNACKBAR='SHOW_SNACKBAR'
